export const USER_ACTION_TYPES = {
  SIGN_UP_START: 'user/SIGN_UP_START',
  SIGN_UP_SUCCESS: 'user/SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'user/SIGN_UP_FAILURE',

  SIGN_IN_START: 'user/SIGN_IN_START',
  SIGN_IN_SUCCESS: 'user/SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'user/SIGN_IN_FAILURE',

  SIGN_OUT_SUCCESS: 'user/SIGN_OUT_SUCCESS',

  UPDATE_PROFILE_START: 'user/UPDATE_PROFILE_START',
  UPDATE_PROFILE_SUCCESS: 'user/UPDATE_PROFILE_SUCCESS',
  UPDATE_PROFILE_FAILURE: 'user/UPDATE_PROFILE_FAILURE',

  GET_USER_START: 'user/GET_USER_START',
  GET_USER_SUCCESS: 'user/GET_USER_SUCCESS',
  GET_USER_FAILURE: 'user/GET_USER_FAILURE',

  SET_ACCESS_TOKEN: 'user/SET_ACCESS_TOKEN',
};
