export const TOURNAMENT_ACTION_TYPES = {
  CREATE_TOURNAMENT_FORM_NEXT: 'tournament/CREATE_TOURNAMENT_FORM_NEXT',
  CREATE_TOURNAMENT_START: 'tournament/CREATE_TOURNAMENT_START',
  CREATE_TOURNAMENT_SUCCESS: 'tournament/CREATE_TOURNAMENT_SUCCESS',
  CREATE_TOURNAMENT_FAILURE: 'tournament/CREATE_TOURNAMENT_FAILURE',

  GET_TOURNAMENTS_START: 'tournament/GET_TOURNAMENTS_START',
  GET_TOURNAMENTS_SUCCESS: 'tournament/GET_TOURNAMENT_SUCCESS',
  GET_TOURNAMENTS_FAILURE: 'tournament/GET_TOURNAMENTS_FAILURE',
};
